"""A 20-day cross-sectional momentum baseline on the bundled sample panel.

Run with `python research/momentum_baseline.py`. No network, no WRDS account:
it reads the synthetic sample prices shipped with the kit, so the numbers it
prints are a check that the pipeline is wired up correctly and nothing more.
They are not evidence about momentum in real markets — the prices are
generated by the two-factor model in `capstone.sample_data`, which has no
momentum in it by construction.

Two details worth keeping when this is pointed at real data:

* The signal is trimmed to its warm-up length before backtesting. `to_weights`
  turns the leading all-NaN signal rows into all-zero weights, which would
  otherwise enter the summary as genuine flat periods and quietly deflate both
  the mean and the volatility.
* The run is logged to the ledger before the result is printed, per
  CLAUDE.md — the trial count only means something if it is incremented
  whether or not the trial turns out to be interesting.
"""

from __future__ import annotations

import pandas as pd

from capstone.backtest import run_backtest, summarize, to_weights
from capstone.runlog import log_run
from capstone.sample_data import load_sample_prices

LOOKBACK = 20
COST_BPS = 10.0
FREQ = "daily"


def momentum_signal(prices: pd.DataFrame, lookback: int = LOOKBACK) -> pd.DataFrame:
    """Trailing `lookback`-day simple return per asset, observed at each date.

    The value at date `t` uses only prices up to and including `t`, which is
    the convention `run_backtest` expects: it shifts positions one period, so
    the signal at `t` earns the return realised at `t+1`.
    """
    return prices.pct_change(lookback)


def mean_turnover(signal: pd.DataFrame) -> float:
    """Mean per-period turnover of the traded book.

    `run_backtest` returns only the net return series, so this recomputes
    turnover the same way it does internally: positions are the weights lagged
    one period, and turnover is the summed absolute change in positions.
    """
    positions = to_weights(signal).shift(1)
    return float(positions.diff().abs().sum(axis=1).mean())


def main() -> None:
    prices = load_sample_prices()
    returns = prices.pct_change()

    # Drop the warm-up rows, where the signal is undefined for every asset.
    signal = momentum_signal(prices).iloc[LOOKBACK:]

    net_returns = run_backtest(signal, returns, cost_bps=COST_BPS)
    summary = summarize(net_returns, freq=FREQ, turnover=mean_turnover(signal))

    log_run(
        "momentum_baseline",
        params={
            "lookback": LOOKBACK,
            "cost_bps": COST_BPS,
            "freq": FREQ,
            "universe": "sample_prices",
            "n_assets": int(signal.shape[1]),
        },
        metrics=summary.as_dict(),
        tags=["momentum", "baseline", "sample-data"],
        notes=(
            "Cross-sectional 20-day momentum on the bundled synthetic sample "
            "panel (deterministic, no RNG drawn here). Pipeline smoke test, "
            "not a claim about real returns."
        ),
    )

    print(f"universe: {signal.shape[1]} assets, {signal.shape[0]} dates after warm-up")
    print(f"signal: trailing {LOOKBACK}-day return, cost_bps={COST_BPS:g}")
    print(summary)


if __name__ == "__main__":
    main()
